# Generated by Django 5.1.2 on 2024-10-21 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.CharField(max_length=36, unique=True)),
                ('campaign_name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('campaign_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leads_generated', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=36, unique=True)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_email', models.EmailField(max_length=100)),
                ('lead_phone', models.CharField(max_length=20)),
                ('lead_source', models.CharField(max_length=100)),
                ('lead_stage', models.CharField(max_length=100)),
                ('date_of_inquiry', models.DateTimeField()),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.campaigndata')),
            ],
        ),
    ]
